"""empty message

Revision ID: 1eedd5dbd0a6
Revises: e97e167f54b4
Create Date: 2026-04-01 19:01:38.582663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eedd5dbd0a6'
down_revision = 'e97e167f54b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('describe', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flat', schema=None) as batch_op:
        batch_op.drop_column('describe')

    # ### end Alembic commands ###
