"""empty message

Revision ID: 47225b8725c9
Revises: 5e257f5cc6b0
Create Date: 2026-05-07 17:26:26.646819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47225b8725c9'
down_revision = '5e257f5cc6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('distric', sa.String(length=500), nullable=False),
    sa.Column('adress', sa.String(length=500), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('square', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('buy_rent', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=50), nullable=False),
    sa.Column('name_owner', sa.String(length=50), nullable=False),
    sa.Column('email_owner', sa.String(length=50), nullable=False),
    sa.Column('phone_owner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
