"""empty message

Revision ID: b70c36d59ebd
Revises: e4a016bee991
Create Date: 2026-05-25 13:33:49.845625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70c36d59ebd'
down_revision = 'e4a016bee991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('old_price', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('distric', sa.VARCHAR(length=500), nullable=False),
    sa.Column('adress', sa.VARCHAR(length=500), nullable=False),
    sa.Column('floor', sa.INTEGER(), nullable=False),
    sa.Column('square', sa.INTEGER(), nullable=False),
    sa.Column('rooms', sa.INTEGER(), nullable=False),
    sa.Column('buy_rent', sa.VARCHAR(length=50), nullable=False),
    sa.Column('owner', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name_owner', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email_owner', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone_owner', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
