"""empty message

Revision ID: e97e167f54b4
Revises: 568cbf02ff32
Create Date: 2026-03-25 22:53:37.759960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97e167f54b4'
down_revision = '568cbf02ff32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('deal_type', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(length=15), nullable=True),
    sa.Column('owner_phone', sa.Integer(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flat')
    # ### end Alembic commands ###
